const express = require('express')
const router = express.Router()
const ctrl = require('../controllers/articleController')
const auth = require('../middleware/auth')
const authorize = require('../middleware/authorize')
const multer = require('multer')
const upload = multer({ dest: 'uploads/' })
router.get('/', auth, ctrl.list)
router.get('/:id', auth, ctrl.get)
router.post('/', auth, authorize('create'), upload.single('image'), ctrl.create)
router.put('/:id', auth, authorize('edit'), ctrl.update)
router.delete('/:id', auth, authorize('delete'), ctrl.delete)
router.post('/:id/publish', auth, authorize('publish'), ctrl.publish)
module.exports = router
